### ISSUE TITLE
error while running make install

### ISSUE THREAD

**Issue by DanielCalvoCerezo** [signals-dev/Orion#75] opened 2020-03-10 09:47 UTC
* Orion version:Latest commit ac44a13
* Python version: 3.6
* Operating System: CENTOS 7

### Description

Did a git pull and was following the install instructions. 
In the make install, it fails due to failing to find pytest-runner.
When looking at the documentation of it (https://pypi.org/project/pytest-runner/) it explicitly states that test and setup requires should be removed and do the test differently.

### What I Did

```
make install
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
pip install .
Processing /home/dcalvo/ORION
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda/anaconda3/envs/sedate36_dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-skzlmbak/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-skzlmbak/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-skzlmbak/
    Complete output (25 lines):
    Download error on https://pypi.org/simple/pytest-runner/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
    No local packages or working download links found for pytest-runner>=2.11.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-skzlmbak/setup.py", line 112, in <module>
        zip_safe=False,
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/anaconda/anaconda3/envs/sedate36_dev/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner>=2.11.1')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [install] Error 1

```
I simply commented the contents of setup_requires and tests_require

**Comment by sarahmish** [comment] 2020-12-31 05:31
Hi @DanielCalvoCerezo! 
Would you mind confirming if this issue still persists?

I can't reproduce it from my side, and since it has been a while since this issue was raised, I am wondering if it is fixed.

**Comment by DanielCalvoCerezo** [comment] 2021-01-12 06:57
Hi Sarah.

Honestly I am not sure. Last time I tried I still needed to tweak the makefile to solve the issue, but that was rather long time ago.

I'll give it a shot whenever I have some time and come back to you.
Please if you have not heard from me by end of next week, don't hesitate coming back at me to kick my chair.

Cheers

Daniel Calvo Cerezo
Sr. Engineer, ADCS & Propulsion.
Tel +352 710 725 5063  *  Mobile +352 691 798 799

**Comment by sarahmish** [comment] 2021-01-12 23:32
No problem! I just wanted to make sure that everything is running smoothly again.

I will close the issue for now, if it is still causing problems feel free to re-open it or even create a new one!
Thanks :)

**Closed by sarahmish** 2021-01-12 23:32 UTC

**Comment by DanielCalvoCerezo** [comment] 2021-01-13 06:50
Ok, thanks a lot Sarah

Daniel Calvo Cerezo
Sr. Engineer, ADCS & Propulsion.
Tel +352 710 725 5063  *  Mobile +352 691 798 799
