### ISSUE TITLE
Saving LSTM model

### ISSUE THREAD

**Issue by kgustafs** [signals-dev/Orion#244] opened 2021-07-26 23:18 UTC
* Orion version: 0.1.7
* Python version: 3.7.0 hea74fb7_0
* Operating System: Windows 10 1909

### Description

Trying to save orion objects formed from tadgan and lstm_dynamic_threshold. We followed issue #206 and are able to save objects from `pipeline='tadgan'` but not a very similar object from `pipeline='lstm_dynamic_threshold'`. 

### What I Did

We set up the LSTM using the following code, very standard, and it works on fitting the model.

```
hyperparameters = {"mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1":
                                {"interval": 1},
                                 'keras.Sequential.LSTMTimeSeriesRegressor#1': 
                                {'epochs': 5, 'verbose': True}
}

orion_lstm = Orion(
    pipeline='lstm_dynamic_threshold',
    hyperparameters=hyperparameters
)

orion_lstm.fit(train_data)

tempfile.tempdir = os.getcwd()

with open("orion_lstm.pkl", "wb") as pickle_file:
    pickle.dump(tgan, pickle_file)
```

Here the crash occurs, with the permissions error looking similar to issue #206 
`
OSError: Unable to create file(unable to open file: name = 'e:\working\test6\tmp7bkr1nhy.hdf5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)
`
The same crash occurs when using the orion.save() function with lstm.

However, when I create and fit a `pipeline='tadgan'` model and `pickle_dump()` in the same way, it works fine, although it does create four separate HDF5 files with tmp* names. I should note that my object `orion_tgan` can also be saved using `orion_tgan.save(FULLPATH),` which I believe means that I have the code version after issue #206 was resolved with PR #216  

I do not understand why the behavior of `pipeline='lstm_dynamic_threshold'` and `pipeline='tadgan'` is different in this respect. 

Do I need to just keep the tmp*.hdf5 files in the directory with the pkl file?

My colleague believes the lstm does not have a `model` entry in the dictionary that is getting iterated over in the save function. He created a pull request PR #243 but our organizational policy prohibits us from signing the CLA.

Has the ability to save LSTM and other models besides TADGAN been lost or corrupted?

**Comment by sarahmish** [comment] 2021-09-14 03:14
Hi @kgustafs, thank you for opening an issue! 
I have investigated your issue and there are two main points:

#### 1. saving LSTM pipeline
the issue is mainly due to the fact that when we create temporary files in windows we do not set them properly. I created an issue in the base library https://github.com/MLBazaar/MLPrimitives/issues/261 to address the problem (PR will follow shortly!)

#### 2. temporary files when saving TadGAN
there are four tempfiles when saving the TadGAN model because TadGAN consists of four networks. You can definitely delete the temporary files without sacrificing or losing your model!

Hope this addresses your issues, and let me know if you have any further question!

**Comment by sarahmish** [comment] 2021-09-30 00:54
Solved in https://github.com/MLBazaar/MLPrimitives/pull/262. Closing.

**Closed by sarahmish** 2021-09-30 00:54 UTC
Labels: bug, question
